services:
  landing:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: DB_HOST
      DB_PORT: DB_PORT
      DB_NAME: ${DB_NAME:-project_landing}
      DB_USER: DB_USER
      DB_PASS: ${DB_PASS:-password}
      APP_BASE_PATH: ${APP_BASE_PATH:-}
    volumes:
      - ./landing:/var/www/html
    ports:
      - "8001:80"
    networks:
      - phpmyadmin_phpmyadminsql-network

networks:
  phpmyadmin_phpmyadminsql-network:
    external: true
